OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-3.5-turbo"
NEO4J_URI = "bolt://3.83.12.92:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "perforation-hardships-lookout"